version: '3'

services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../config/proxy/proxy.conf:/etc/nginx/conf.d/default.template:ro
      - ../config/proxy/ssl:/ssl:rw
    env_file:
      - "../.env"
    command: /bin/sh -c "envsubst '$$NGINX_HOST_SUFFIX' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"